--require("config.packer")
require("config.lazy_config")
require("config.remaps")
require("config.treesitter")
require("config.colorscheme")
require("config.coc_config")
require("config.rust_tool")
require("config.toggle_term")
print("Welcome David")
